"""SQLAlchemy database models for Open Guardian Kids (OGK).
Defines Parent, Device, PairingCode, and HeartbeatLog models.
"""

from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship

try:
    from .database import Base
except ImportError:
    from database import Base


def utc_now():
    """Return timezone-aware current UTC time."""
    return datetime.now(timezone.utc)


class Parent(Base):
    """Parent account model for managing authentication and owned devices."""
    __tablename__ = "parents"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=utc_now, nullable=False)

    devices = relationship("Device", back_populates="parent", cascade="all, delete-orphan")
    pairing_codes = relationship("PairingCode", back_populates="parent", cascade="all, delete-orphan")


class Device(Base):
    """Child's device enrolled under a parent account."""
    __tablename__ = "devices"

    id = Column(Integer, primary_key=True, index=True)
    parent_id = Column(Integer, ForeignKey("parents.id", ondelete="CASCADE"), nullable=False)
    device_name = Column(String(100), default="Windows PC", nullable=False)
    device_fingerprint = Column(String(128), unique=True, index=True, nullable=False)
    status = Column(String(20), default="offline", nullable=False)
    last_seen = Column(DateTime, nullable=True)

    parent = relationship("Parent", back_populates="devices")
    heartbeats = relationship("HeartbeatLog", back_populates="device", cascade="all, delete-orphan")


class PairingCode(Base):
    """Temporary 8-character pairing code generated by parents to enroll child agents."""
    __tablename__ = "pairing_codes"

    id = Column(Integer, primary_key=True, index=True)
    parent_id = Column(Integer, ForeignKey("parents.id", ondelete="CASCADE"), nullable=False)
    code = Column(String(8), index=True, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    is_used = Column(Boolean, default=False, nullable=False)

    parent = relationship("Parent", back_populates="pairing_codes")


class HeartbeatLog(Base):
    """Periodic heartbeat telemetry sent from child agents."""
    __tablename__ = "heartbeat_logs"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("devices.id", ondelete="CASCADE"), nullable=False)
    timestamp = Column(DateTime, default=utc_now, nullable=False)
    status_payload = Column(Text, nullable=True)

    device = relationship("Device", back_populates="heartbeats")
